name: flutter_id3_reader
description: plugin to get id3 metadata and album art for a mp3 file
version: 1.0.0
repository: https://github.com/talamaska/flutter_id3_reader/tree/master/flutter_id3_reader_platform_interface

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_id3_reader_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        pluginClass: FlutterId3ReaderPlugin
        package: com.pehlivanov.zlati.flutter_id3_reader
